services:
  frontend:
    build: 
      context: ./frontend-app
      dockerfile: Dockerfile  
    container_name : container_frontend
    environment : 
      REACT_APP_BACKEND_URL : "http://backend:3001" 
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile  
    container_name: container_backend_react
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks: 
      - app-network
    
  database:
    image : mysql:5.6
    container_name: container_sql
    environment:
       MYSQL_ROOT_PASSWORD: myrootpassword
       MYSQL_DATABASE: dbsmschool
       MYSQL_USER: test
       MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
   
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: container_php_my_admin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - app-network


networks:
    app-network:
    
     
    
    